### PR TITLE
Register exit handler(s) to detect premature call to [quick_]exit().

### PR DESCRIPTION
**Pull request by amirkamil**

### CODE REVIEW

**Comment by amirkamil** [comment]
This isn't foolproof.

- Ideally, the `incomplete` bool should be set to false upon `TestSuite` creation, but that breaks the regression tests.
- Students can still call `_Exit()` directly. No way to detect that programmatically.

**Comment by amirkamil** [comment]
Students can also call `exit()` in dynamic initialization, which wouldn't be caught in the current setup. If we made `incomplete` false upon creating a `TestSuite`, then it would be a coin toss whether or not it would be caught.

~~As for `_Exit()`, we can do something Very Bad (TM) and `#define _Exit` to something else.~~ That wouldn't work since they're not #including `unit_test_framework.h` from their implementation modules.

**Comment by jamesjuett** [comment]
Something even worse would be to do some preprocessing and `rm` files that contain `_Exit` (or other bad things). We could make the failure a bit more graceful by giving public feedback for the test that kills their code.

**Comment by amirkamil** [comment]
Done.

**Pull request merged**
